### ISSUE TITLE
Add normal non-root user to docker group.

### ISSUE THREAD

**Issue by blmhemu** [darkwizard242/ansible-role-docker#7]
I need to do sudo for every docker run which is frustrating.
I think we need to add the non-root user(s) to docker group as presented in https://docs.docker.com/engine/install/linux-postinstall/
Please see if you can raise a PR for that ?

```
sudo usermod -aG docker $USER
```

I think it should be simple one:
```
- name: Add the users {{non_root_users}} to docker group
  ansible.builtin.user:
    name: {{item}}
    append: yes
    group: {{docker_group}}
 loop: {{non_root_users}}
```
